networks:
  default:

services:
  proxy:
    image: ghcr.io/libops/vault-proxy:local
    build: .
    networks:
      default:
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/config.yaml:ro
    command:
      - -config
      - /config.yaml
    read_only: true
