name: Create release

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, 'skip-release')
    uses: libops/.github/.github/workflows/bump-release.yaml@578137212ead4ab4059e95df17fa30e9b7ac4aed
    with:
      workflow_file: goreleaser.yaml
    permissions:
      contents: write
      actions: write
